version: '2'
services:
  zookeeper01:
    image: daocloud.io/daocloud/zookeeper:v0.4
    container_name: zookeeper01
    hostname: zookeeper01
    labels:
      io.daocloud.group: zookeeper-cluster
    networks:
    - kf0
    environment:
    - affinity:container!=zookeeper*
    - SERVER_ID=1
    - ZK_SERVERS=server.1=zookeeper01:2888:3888,server.2=zookeeper02:2888:3888,server.3=zookeeper03:2888:3888
    restart: unless-stopped
    command: /usr/local/zookeeper/zookeeper-cluster.sh start
    cpu_quota: 50000
    mem_limit: 2147483648
    ports:
      - "2181:2181"
  zookeeper02:
    image: daocloud.io/daocloud/zookeeper:v0.4
    container_name: zookeeper02
    hostname: zookeeper02
    labels:
      io.daocloud.group: zookeeper-cluster
    networks:
    - kf0
    environment:
    - affinity:container!=zookeeper*
    - SERVER_ID=2
    - ZK_SERVERS=server.1=zookeeper01:2888:3888,server.2=zookeeper02:2888:3888,server.3=zookeeper03:2888:3888
    restart: unless-stopped
    command: /usr/local/zookeeper/zookeeper-cluster.sh start
    cpu_quota: 50000
    mem_limit: 2147483648
  zookeeper03:
    image: daocloud.io/daocloud/zookeeper:v0.4
    container_name: zookeeper03
    hostname: zookeeper03
    labels:
      io.daocloud.group: zookeeper-cluster
    networks:
    - kf0
    environment:
    - affinity:container!= zookeeper*
    - SERVER_ID=3
    - ZK_SERVERS=server.1=zookeeper01:2888:3888,server.2=zookeeper02:2888:3888,server.3=zookeeper03:2888:3888
    restart: unless-stopped
    command: /usr/local/zookeeper/zookeeper-cluster.sh start
    cpu_quota: 50000
    mem_limit: 2147483648
networks:
  kf0:
    external: true
