version: '2'
services:
  mysql:
    image: daocloud.io/library/mysql:latest
    user: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=dangerous
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    cpu_quota: 50000
    mem_limit: 1073741824
    hostname: mysql
    networks:
      kf0:
        aliases:
        - mysql
networks:
  kf0:
    external: true
volumes:
  mysql-data: