version: '2'
services:
  broker01:
    image: daocloud.io/daocloud/kafka:v0.1
    container_name: broker01
    hostname: broker01
    labels:
      io.daocloud.group: kafka-cluster
    networks:
    - kf0
    environment:
    - ZOOKEEPER_SERVERS=zookeeper01:2181,zookeeper02:2181,zookeeper03:2181
    - BROKER_ID=0
    restart: never
    command: start broker
    cpu_quota: 90000
    mem_limit: 2147483648
    ports:
      - "9092:9092"
  broker02:
    image: daocloud.io/daocloud/kafka:v0.1
    container_name: broker02
    hostname: broker02
    labels:
      io.daocloud.group: kafka-cluster
    networks:
    - kf0
    environment:
    - ZOOKEEPER_SERVERS=zookeeper01:2181,zookeeper02:2181,zookeeper03:2181
    - BROKER_ID=1
    restart: never
    command: start broker
    cpu_quota: 90000
    mem_limit: 2147483648
  broker03:
    image: daocloud.io/daocloud/kafka:v0.1
    container_name: broker03
    hostname: broker03
    labels:
      io.daocloud.group: kafka-cluster
    networks:
    - kf0
    environment:
    - ZOOKEEPER_SERVERS=zookeeper01:2181,zookeeper02:2181,zookeeper03:2181
    - BROKER_ID=2
    restart: never
    command: start broker
    cpu_quota: 90000
    mem_limit: 2147483648
networks:
  kf0:
    external: true
