version: '2'
services:
  redis: 
    image: daocloud.io/redis:latest
    ports: 
      - "6379:6379"
    restart: unless-stopped
    cpu_quota: 50000
    mem_limit: 2147483648
    networks:
      kf0:
        aliases:
          - redis
networks:
  kf0:
    external: true